apiVersion: v1
kind: Service
metadata:
  name: {{ include "mintdb.fullname" . }}
  labels:
    {{- include "mintdb.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mintdb.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP