apiVersion: v1
kind: Service
metadata:
  name: mintdb-stack
spec:
  selector:
    app: mintdb-stack
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP